### ISSUE TITLE
Lambda Timeout has been increased to 30 seconds, but not the message visibility in SQS

### ISSUE THREAD

**Issue by pauljflo** [cloudentity/aws-authorizer-cdk#3]
Currently receiving this error message
Queue visibility timeout: 10 seconds is less than Function timeout: 30 seconds

Looks like the lambda timeout was increased yesterday from 10 seconds to 30. 
The SQS message visibility and lambda timeout should match.

**Comment by holowinski** [comment]
Thanks for reporting.
Fixed in https://github.com/cloudentity/aws-authorizer-cdk/pull/5
